---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 21:02
---
---@class EndPanel End UI页面
local EndPanel = {}
--- 打开页面
function EndPanel:Open()
    local panel = UIManager.Instance:GetPanel("EndPanel");
    if (panel == nil) then
        EndPanel:Ctor()
    end
end
--- 构造函数
function EndPanel:Ctor()
    self.panel = UIManager.Instance:ShowPanel("EndPanel");
    self.transform = self.panel.transform
    self.gameObject = self.panel.gameObject
    self.panel.reStartBtn.onClick:AddListener(function()
        GameData.CurrentLevel = 1;
        GameData.CurrentScore = 0;
        GameData.TargetScore = 1000;

        UIManager.Instance:GetPanel("GamePanel").GameTime = 100;
        GameControl:CreateStar();
        self:Close();
    end)
end

function EndPanel.Close()
    UIManager.Instance:HidePanel("EndPanel");
end

return EndPanel