---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 23:19
---
---@class GamePanel Game UI页面
local GamePanel = {}
local this = GamePanel

--- 开始游戏
function GamePanel.StartGame()
    this:Open()
    GameControl:Start()
end
--- 打开页面
function GamePanel:Open()
    self.panel = UIManager.Instance:GetPanel("GamePanel");
    if (self.panel == nil) then
        GamePanel:Ctor()
    end
    self.cover = self.transform:Find("Image").gameObject;
end
--- 构造函数
function GamePanel:Ctor()
    self.panel = UIManager.Instance:ShowPanel("GamePanel");
    self.transform = self.panel.transform
    self.gameObject = self.panel.gameObject
    self.panel.remainStarScore.gameObject:SetActive(false);
    self.panel.SettingBtn.onClick:AddListener(function()
        --显示暂停面板
        SettingPanel.Open()
    end)
    self.winPanel = self.transform:Find("WinPanel")
    self:HideWin()
end
--- 开始游戏
function GamePanel:Start()
    self.panel.gameStart = true;
    self.panel.GameTime = 100
    GameData.CurrentScore = 0;
    GamePanel:Refresh()
end
--- 刷新页面显示
function GamePanel:Refresh()
    self.panel:RefreshText(GameData.CurrentLevel, GameData.TargetScore, GameData.CurrentScore, GameData.remainStarScore)
end
--- 显示win
function GamePanel:ShowWin()
    self.winPanel.gameObject:SetActive(true)
end
--- 关闭win
function GamePanel:HideWin()
    self.winPanel.gameObject:SetActive(false)
end

--- 关闭页面
function GamePanel:Close()
    UIManager.Instance:HidePanel("GamePanel");
end

return GamePanel