---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 21:02
---
---@class SettingPanel Setting UI页面
local SettingPanel = {}
--- 打开页面
function SettingPanel:Open()
    local panel = UIManager.Instance:GetPanel("SettingPanel");
    if (panel == nil) then
        SettingPanel:Ctor()
    end
end
--- 构造函数
function SettingPanel:Ctor()
    self.panel = UIManager.Instance:ShowPanel("SettingPanel");
    self.transform = self.panel.transform
    self.gameObject = self.panel.gameObject

    self.panel.CloseBtn.onClick:AddListener(function()
        SettingPanel.Close()
    end)

    self.panel.BkMusic.onValueChanged:AddListener(function(value)
        if (value) then
            MusicMgr.GetInstance():PlayBkMusic("Bk");
        else
            MusicMgr.GetInstance():StopBKMusic();
        end
    end)

    self.panel.BkValue.onValueChanged:AddListener(function(value)
        MusicMgr.GetInstance():ChangeBKValue(value);
    end)
end
--- 关闭页面
function SettingPanel.Close()
    UIManager.Instance:HidePanel("SettingPanel");
end

return SettingPanel