---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 21:02
---
---@class StartPanel Start UI页面
local StartPanel = {}

--- 打开页面
function StartPanel.Open()
    local panel = UIManager.Instance:GetPanel("StartPanel");
    if (panel == nil) then
        StartPanel:Ctor()
    end
end

--- 构造函数
function StartPanel:Ctor()
    self.panel = UIManager.Instance:ShowPanel("StartPanel");
    self.transform = self.panel.transform
    self.gameObject = self.panel.gameObject
    self.panel.Startbutton.onClick:AddListener(function()
        StartPanel.Close()
        GamePanel.StartGame()
    end)
    self.panel.TestBtn.onClick:AddListener(function()
        StartPanel.Close()
        TestPanel.Open()
    end)
end

--- 关闭页面
function StartPanel.Close()
    UIManager.Instance:HidePanel("StartPanel");
end

return StartPanel