---
--- Generated by EmmyLua(https:--github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 21:02
---
---@class TestPanel Test UI页面
local TestPanel = {}
--- 打开页面
function TestPanel:Open()
    local panel = UIManager.Instance:GetPanel("TestPanel");
    if (panel == nil) then
        TestPanel:Ctor()
    end
end
--- 构造函数
function TestPanel:Ctor()
    self.panel = UIManager.Instance:ShowPanel("TestPanel");
    self.transform = self.panel.transform
    self.gameObject = self.panel.gameObject
    self.panel.CloseBtn.onClick:AddListener(function()
        TestPanel.Close()
        StartPanel:Open()
    end)
end
--- 关闭页面
function TestPanel.Close()
    UIManager.Instance:HidePanel("TestPanel");
end

return TestPanel