---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 23:27
---

---@class GameData 游戏常量
GameData = {}

---棋盘的大小 行数
GameData.row = 12;
---棋盘的大小 列数
GameData.colume = 10;
---当前关卡
GameData.CurrentLevel = 1;
---当前分数
GameData.CurrentScore = 0;
---当前目标分数
GameData.TargetScore = 1000;
---历史最高分数
GameData.maxGameScore = 0;
---当前的游戏状态
GameData.gameState = GameState.Load
---剩余星星得分
GameData.remainStarScore = 0

return GameData;