---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by GILLAR.
--- DateTime: 2023/12/15 21:38
---
RectTransform = CS.UnityEngine.RectTransform
GameObject = CS.UnityEngine.GameObject
Transform = CS.UnityEngine.Transform
Vector3 = CS.UnityEngine.Vector3
Vector2 = CS.UnityEngine.Vector2
Random = CS.UnityEngine.Random
Physics2D = CS.UnityEngine.Physics2D
LayerMask = CS.UnityEngine.LayerMask
Debug = CS.UnityEngine.Debug
Color = CS.UnityEngine.Color
CoroutineTool = CS.CoroutineTool

UIManager = CS.UIManager
BasePanel = CS.BasePanel
ResMgr = CS.ResMgr
MusicMgr = CS.MusicMgr
Star = CS.Star

cs_coroutine = require("Common.cs_coroutine")
require("Common.LuaUtil")
require("Common.StringUtil")
require("Common.TableUtil")

GameControl = require "GameControl"
GameState = require "Common.GameState"
GameData = require "Common.GameData"

StartPanel = require "UI.StartPanel"
LoginPanel = require "UI.LoginPanel"
TestPanel = require "UI.TestPanel"
GamePanel = require "UI.GamePanel"
EndPanel = require "UI.EndPanel"
SettingPanel = require "UI.SettingPanel"

